#!/usr/bin/env bash
#
# One-time setup after git clone. Works on macOS, Linux, and Windows (Git Bash / WSL).
#
# Usage (from the cloned scripts directory):
#   ./setup.sh
#   bash setup.sh              # if "permission denied" on fresh clone
#   ./setup.sh --no-global     # skip ~/.local/bin wrappers; use ./flutter-scripts.sh only
#   ./setup.sh --project PATH  # set default Flutter project for this machine

set -euo pipefail

_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../../lib/repo_bootstrap.sh
source "$_SCRIPT_DIR/../../lib/repo_bootstrap.sh"
ROOT="$_REPO_ROOT"
INSTALL_GLOBAL="true"
PROJECT_HINT=""

print_usage() {
  cat <<'EOF'
Bootstrap shell scripts after git clone.

Usage:
  ./setup.sh [--no-global] [--project PATH]

Options:
  --no-global     Do not install commands to ~/.local/bin (run ./flutter-scripts.sh instead)
  --project PATH  Suggest PROJECT_ROOT for this app (written to setup.env snippet)
  -h, --help      Show this help

After setup, add to ~/.zshrc or ~/.bashrc:
  source "/path/to/this/clone/shell-profile.snippet"

Or use FLUTTER_SCRIPTS_HOME so the path stays portable across machines:
  export FLUTTER_SCRIPTS_HOME="$HOME/path/to/cloned/scripts"
  source "${FLUTTER_SCRIPTS_HOME}/shell-profile.snippet"
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --no-global)
      INSTALL_GLOBAL="false"
      shift
      ;;
    --project)
      PROJECT_HINT="$2"
      shift 2
      ;;
    -h|--help)
      print_usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      print_usage >&2
      exit 1
      ;;
  esac
done

if ! command -v bash >/dev/null 2>&1; then
  echo "bash is required." >&2
  exit 1
fi

echo "==> Scripts directory: $ROOT"

find "$ROOT" \( -path "$ROOT/scripts/*.sh" -o -path "$ROOT/scripts/*/*.sh" -o -path "$ROOT/*.sh" \) -type f -print0 2>/dev/null \
  | xargs -0 chmod +x 2>/dev/null || true

_detect_flutter_project() {
  local dir="$1"
  while [[ "$dir" != "/" ]]; do
    if [[ -f "$dir/pubspec.yaml" && -d "$dir/lib" ]]; then
      printf '%s\n' "$(cd "$dir" && pwd)"
      return 0
    fi
    dir="$(dirname "$dir")"
  done
  return 1
}

if [[ -z "$PROJECT_HINT" ]]; then
  PROJECT_HINT="$(_detect_flutter_project "$ROOT/.." || true)"
  if [[ -z "$PROJECT_HINT" ]]; then
    PROJECT_HINT="$(_detect_flutter_project "$ROOT" || true)"
  fi
fi

SETUP_ENV="$ROOT/setup.env"
{
  echo "# Generated by setup.sh — source from shell-profile.snippet or ~/.zshrc"
  echo "export FLUTTER_SCRIPTS_HOME=\"$ROOT\""
  echo "export SCRIPTS_DIR=\"$ROOT\""
  if [[ -n "$PROJECT_HINT" ]]; then
    echo "export PROJECT_ROOT=\"$PROJECT_HINT\""
  fi
} >"$SETUP_ENV"

if [[ "$INSTALL_GLOBAL" == "true" ]]; then
  echo "==> Installing global commands (wrappers point at this clone)..."
  "$ROOT/install_global.sh" --in-place
else
  echo "==> Skipping global install (--no-global)."
  echo "    Run scripts via: $ROOT/flutter-scripts.sh"
fi

echo ""
echo "==> Setup complete."
echo ""
echo "Add ONE of these to ~/.zshrc (replace path if you move the clone):"
echo ""
echo "  # Option A — source setup.env (sets FLUTTER_SCRIPTS_HOME + PROJECT_ROOT)"
echo "  source \"$SETUP_ENV\""
echo "  source \"\$FLUTTER_SCRIPTS_HOME/shell-profile.snippet\""
echo ""
echo "  # Option B — single line (self-locating snippet)"
echo "  source \"$ROOT/shell-profile.snippet\""
echo ""
if [[ -n "$PROJECT_HINT" ]]; then
  echo "Detected Flutter project: $PROJECT_HINT"
  echo ""
fi
echo "Try:"
echo "  source \"$SETUP_ENV\" && source \"\$FLUTTER_SCRIPTS_HOME/shell-profile.snippet\""
echo "  flutter-scripts --list"
echo "  flutter-build-android --project \"${PROJECT_HINT:-<your-app>}\""
echo ""
echo "Windows: use Git Bash or WSL, then run the same commands."
